### ISSUE TITLE
What is the hairpin.fa file's exact content?

### ISSUE THREAD

**Issue by abearab** [hesselberthlab/sc-haircut#3]
Dear Hesselberth lab members, 

I'm trying to replicate your analysis using the published GEO raw data. How can I use your `hairpin.fa` file which has mentioned for the repair count pipeline? I could not understand how to find it or maybe generate it. If I want to prepare that correctly, I'm not sure how should I deal with the hairpins that could be modified in this experiment. If you can push your own `hairpin.fa` file into this repo then it would be awesome. 

Looking forward to hearing back from you. 

Best

**Comment by jayhesselberth** [comment]
@mandylr can you add this file to the repo?

**Comment by mandylr** [comment]
Added the [hairpin fasta file](https://github.com/hesselberthlab/sc-haircut/tree/master/data). It contains the hairpin sequences used in the paper. Not all hairpins are present in each experiment. The modified bases are present in the fasta in their non-modified form (e.g. U -> T, and the abasic site is encoded as a normal basepair (G:C)).
